cli-wallet:
  image: mauritso/bitshares-2-cli-wallet
  volumes:
    - ./wallet:/wallet

exchange-bot:
  image: mauritso/docker-exchangebot
  volumes:
    - ./docker-exchangebot:/usr/src/app
  links:
    - cli-wallet
